name: amls_ii-final-uceezl8
channels:
  - defaults
dependencies:
  - python=3.9
  - black                               # formatter
  - scikit-learn                        # confusion matrix
  - pandas                              # load dataframe
  - ipython                             # debugging
  - pillow                              # read images
  - torchvision                         # pre-processing
  - pytorch                             # build models
  - pytorch-cuda=11.8                   # pytorch for GPU
  - matplotlib                          # draw figures
  - pip:
    - -r requirements.txt
