name: amls_ii-final-uceezl8
channels:
  - defaults
dependencies:
  - python=3.9
  - black
  - scikit-learn
  - pandas
  - ipython
  - pillow
  - torchvision
  - pytorch
  - pytorch-cuda=11.8
  - matplotlib
  - pip:
    - -r requirements.txt
