DEFAULT_DATASET_FOLDER = "Datasets/imagefolder"
DATALOADER_PREFETCH_FACTOR = 1
DEFAULT_PRETRAINED_MODEL = "facebook/convnextv2-base-1k-224"
DEFAULT_RANDOM_SEED = 42
DEFAULT_BATCH_SIZE = 180
DEFAULT_TRAIN_EPOCHS = 16
DEAULT_NUM_WORKERS = 5
